/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as Char126offlineRouteImport } from './routes/~offline'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'
import { Route as ShowsSearchRouteImport } from './routes/shows.search'
import { Route as ShowsImportMediaTypeTmdbIdRouteImport } from './routes/shows.import.$mediaType.$tmdbId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const Char126offlineRoute = Char126offlineRouteImport.update({
  id: '/~offline',
  path: '/~offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/shows/$id',
  path: '/shows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsSearchRoute = ShowsSearchRouteImport.update({
  id: '/shows/search',
  path: '/shows/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsImportMediaTypeTmdbIdRoute =
  ShowsImportMediaTypeTmdbIdRouteImport.update({
    id: '/shows/import/$mediaType/$tmdbId',
    path: '/shows/import/$mediaType/$tmdbId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/tracking': typeof TrackingRoute
  '/watchlist': typeof WatchlistRoute
  '/~offline': typeof Char126offlineRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/search': typeof ShowsSearchRoute
  '/shows/import/$mediaType/$tmdbId': typeof ShowsImportMediaTypeTmdbIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/tracking': typeof TrackingRoute
  '/watchlist': typeof WatchlistRoute
  '/~offline': typeof Char126offlineRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/search': typeof ShowsSearchRoute
  '/shows/import/$mediaType/$tmdbId': typeof ShowsImportMediaTypeTmdbIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/timeline': typeof TimelineRoute
  '/tracking': typeof TrackingRoute
  '/watchlist': typeof WatchlistRoute
  '/~offline': typeof Char126offlineRoute
  '/shows/$id': typeof ShowsIdRoute
  '/shows/search': typeof ShowsSearchRoute
  '/shows/import/$mediaType/$tmdbId': typeof ShowsImportMediaTypeTmdbIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/login'
    | '/more'
    | '/notifications'
    | '/register'
    | '/timeline'
    | '/tracking'
    | '/watchlist'
    | '/~offline'
    | '/shows/$id'
    | '/shows/search'
    | '/shows/import/$mediaType/$tmdbId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/login'
    | '/more'
    | '/notifications'
    | '/register'
    | '/timeline'
    | '/tracking'
    | '/watchlist'
    | '/~offline'
    | '/shows/$id'
    | '/shows/search'
    | '/shows/import/$mediaType/$tmdbId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/login'
    | '/more'
    | '/notifications'
    | '/register'
    | '/timeline'
    | '/tracking'
    | '/watchlist'
    | '/~offline'
    | '/shows/$id'
    | '/shows/search'
    | '/shows/import/$mediaType/$tmdbId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  TimelineRoute: typeof TimelineRoute
  TrackingRoute: typeof TrackingRoute
  WatchlistRoute: typeof WatchlistRoute
  Char126offlineRoute: typeof Char126offlineRoute
  ShowsIdRoute: typeof ShowsIdRoute
  ShowsSearchRoute: typeof ShowsSearchRoute
  ShowsImportMediaTypeTmdbIdRoute: typeof ShowsImportMediaTypeTmdbIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/~offline': {
      id: '/~offline'
      path: '/~offline'
      fullPath: '/~offline'
      preLoaderRoute: typeof Char126offlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/shows/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/search': {
      id: '/shows/search'
      path: '/shows/search'
      fullPath: '/shows/search'
      preLoaderRoute: typeof ShowsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/import/$mediaType/$tmdbId': {
      id: '/shows/import/$mediaType/$tmdbId'
      path: '/shows/import/$mediaType/$tmdbId'
      fullPath: '/shows/import/$mediaType/$tmdbId'
      preLoaderRoute: typeof ShowsImportMediaTypeTmdbIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  TimelineRoute: TimelineRoute,
  TrackingRoute: TrackingRoute,
  WatchlistRoute: WatchlistRoute,
  Char126offlineRoute: Char126offlineRoute,
  ShowsIdRoute: ShowsIdRoute,
  ShowsSearchRoute: ShowsSearchRoute,
  ShowsImportMediaTypeTmdbIdRoute: ShowsImportMediaTypeTmdbIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
